### PR TITLE
Add Underground Timer UI

### PR DESCRIPTION
**Pull request by whuras**

### CODE REVIEW

**Review by danielwiktorczyk — APPROVED** [review]
Wonderful!  Thank you for the colors!

**Review by shifatkhan — APPROVED** [review]
Looks awesome!

**Review by shifatkhan — CHANGES_REQUESTED** [review]
As stated in discord (just leaving this here for the record)
image

**Review by shifatkhan — APPROVED** [review]
Noicee! All fixed up 👍

**Pull request merged**
