### PR TITLE
Feature/environment concept #35

### PR DESCRIPTION
**Pull request by tiffhc**
Added all the models (and making prefabs for some but not all), started creating materials from shaders and started setting the micro design for the 4 biomes

### CODE REVIEW

**Comment by shifatkhan** [comment]
The models are so pretty *-*
Btw the pointy rocks seem to be see-through
image

**Review by eli-lam — CHANGES_REQUESTED** [review]
Models are rotated

**Review by eli-lam — APPROVED** [review]
Nice job!

**Review by danielwiktorczyk — CHANGES_REQUESTED** [review]
Please organize the Assets/Models into separate folders!! --> make sure to do this within the unity editor, and NOT in windows. Reason being, unity manages .meta files that don't play nicely when we don't manage them properly

Also, squash your commits into one, and check the commit naming convention guidelines

**Review by danielwiktorczyk — APPROVED** [review]
Looks good! Thanks for the changes!

**Review by shifatkhan — APPROVED** [review]

**Pull request merged**
