### PR TITLE
Add background noise for speaking

### PR DESCRIPTION
**Pull request by zhengHugo**
Add background noise when speaking. Possibly can be used in the underground scene.

Use a white noise as a placeholder audio file. 

The speech detection is not very sharp. In my case, it is very reluctant to cut-off my voice, and the experience is kind of laggy.

### CODE REVIEW

**Review by danielwiktorczyk — CHANGES_REQUESTED** [review]
As discussed: 

--> add threshold for speaking, which should be adjustable. Maybe make a gameobject with a script attached to play with the sliders? 
--> people NOT underground should be able to hear others who are also not underground crisply; otherwise, noise

--> if possible, add a Team filter. for now, just a boolean

**Comment by zhengHugo** [comment]
- Add team selector
- Add underground tick box
- Fix bug: only add noise when the underground person is speaking (not tested yet, at least two people needed for testing)
- Add an audio level threshold to play noise

**Review by danielwiktorczyk — CHANGES_REQUESTED** [review]
Check your sprite! It's not showing up for us

**Review by shifatkhan — APPROVED** [review]
Awesome! Sprite updates correctly now when speaking 👍

**Review by danielwiktorczyk — APPROVED** [review]
Great work! Let's get this in haha

**Pull request merged**
